import Head from "next/head";
import Header from "./Header";

export default function Layout({ title, children }) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.png" />
			</Head>
			<main>
				<Header />
				{children}
			</main>
		</>
	)
}